import { Router, Request, Response } from "express";
import { getStatus, forceResetSession } from "../whatsapp";
import { checkSecret } from "../utils";
import { config } from "../config";

const router = Router();

function checkPairSecret(provided: string) {
  // Runtime read pour faciliter les tests qui mutent process.env — en prod
  // ces valeurs sont figées au boot de toute façon.
  const raw = process.env.PAIR_SECRET || config.PAIR_SECRET;
  const expected = (raw && raw !== "changeme_generer_un_vrai_secret") ? raw : undefined;
  return checkSecret(provided, expected, "PAIR_SECRET");
}

// GET /api/wa/status — minimal info (NO QR exposed publicly)
router.get("/status", (_req: Request, res: Response) => {
  const status = getStatus();
  res.json({
    ready: status.ready,
    loading: status.loading,
    has_qr: !!status.qr_data_url,
  });
});

// POST /api/wa/qr — get the QR code (gated by PAIR_SECRET)
router.post("/qr", async (req: Request, res: Response) => {
  const check = checkPairSecret(String(req.body?.secret || ""));
  if (!check.ok) {
    res.status(check.status).json({ error: check.error });
    return;
  }

  // Wait up to 30s for the QR to be generated by the client
  let status = getStatus();
  let waited = 0;
  while (!status.qr_data_url && waited < 30000 && !status.ready) {
    await new Promise((r) => setTimeout(r, 500));
    waited += 500;
    status = getStatus();
  }

  if (!status.qr_data_url) {
    res.status(404).json({ error: "Pas de QR disponible" });
    return;
  }

  res.json({ qr_data_url: status.qr_data_url });
});

// POST /api/wa/reset-session — soupape de secours : wipe data/baileys_auth/
// et relance l'init. Utile quand le bot reste bloqué en "loading" sans QR
// (ex: creds stales après redéploiement). Gated par PAIR_SECRET pour éviter
// qu'un attaquant casse la session liée.
router.post("/reset-session", async (req: Request, res: Response) => {
  const check = checkPairSecret(String(req.body?.secret || ""));
  if (!check.ok) {
    res.status(check.status).json({ error: check.error });
    return;
  }
  try {
    await forceResetSession();
    res.json({ ok: true, message: "Session WhatsApp réinitialisée. Un nouveau QR va apparaître." });
  } catch (err: any) {
    res.status(500).json({ error: err?.message || "Reset failed" });
  }
});

export default router;
